version: '3'

services:
  workspace:
    tty: true
    build: docker/node
    ports:
      - 80:3000
    volumes:
      - ./:/var/www
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_DOMAIN_NAME=http://localhost
      - GA_TRACKING_ID=G-3NHR8R6NTJ
    command: >
      bash -c "
        npm install
        npm run dev
      "